# -*- coding: utf-8 -*-
"""Task 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Xfa3G0M9O3vLYkGs0OK5VfKACl95x7A
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('Titanic-Dataset.csv')
print(df.head())

print(df.info())

print(df.isnull().sum())

print(df.info())

df['Age'].fillna(df['Age'].median())
df['Embarked'].fillna(df['Embarked'].mode()[0])
if 'Cabin' in df.columns:
    df.drop('Cabin', axis=1, inplace=True)

le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])  # Male = 1, Female = 0
df['Embarked'] = le.fit_transform(df['Embarked'])

if 'Embarked' in df.columns and df['Embarked'].isnull().any():
    if not df['Embarked'].mode().empty:
        df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])
    else:
        print("No mode found for 'Embarked'. Cannot fill missing values.")

df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

# Convert to string to avoid numeric errors
df['Embarked'] = df['Embarked'].astype(str)

# Applied one-hot encoding
df = pd.get_dummies(df, columns=['Embarked'], drop_first=True)

df.rename(columns={
    'Embarked_1': 'Embarked_Q',
    'Embarked_2': 'Embarked_S'
}, inplace=True)

print(df.head())

for col in ['Name', 'Ticket', 'PassengerId']:
    if col in df.columns:
        df.drop(col, axis=1, inplace=True)

print(df.head())

plt.figure(figsize=(10, 4))
sns.boxplot(data=df[['Age', 'Fare']])
plt.title('Boxplot of Age and Fare')
plt.show()

Q1 = df[['Age', 'Fare']].quantile(0.25)
Q3 = df[['Age', 'Fare']].quantile(0.75)
IQR = Q3 - Q1
df = df[~((df[['Age', 'Fare']] < (Q1 - 1.5 * IQR)) | (df[['Age', 'Fare']] > (Q3 + 1.5 * IQR))).any(axis=1)]

print(df[['Age', 'Fare']].describe())

scaler = StandardScaler()
df[['Age', 'Fare']] = scaler.fit_transform(df[['Age', 'Fare']])

print(df.head())